name: Deployment
# Workflow runs when Pull Requests to stage or main are opened
# Or when a push is commited to stage or main
on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [dev, master]
  push:
    branches: [ dev, master ]
jobs:
  deploy:
    if: github.repository == 'ludeku/ludeku.net' # only run here
    runs-on: ubuntu-latest
    # environment:
    #   name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ENV Variables
        uses: actions/github-script@v3
        with:
          script: |
            const path = require('path');
            const setup = require(path.resolve('./.github/ga-env.js'));
            await setup({ github, context, core });
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: | 
            ${{ env.CICD_ENV_dockerImage }}
          tags: |
            type=sha
      - name: Docker Setup
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DEPLOY_USR }}
          password: ${{ secrets.DEPLOY_PSW }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Deploy to Swarm
        uses: Ludeku/deploy@v1
        with:
          stack: ${{ env.CICD_ENV_deploymentName }}
          image: '${{ env.CICD_ENV_dockerImage }}:${{ env.CICD_ENV_tagName }}'
          apiKey: ${{secrets.DEPLOY_API_KEY}}
          deployUrl: ${{ env.CICD_ENV_deployUrl }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            This pr has been deployed and is available at https://${{ env.CICD_ENV_deployUrl }}
